---
title: "Introduction to Data Science (STAT 0118)"
output:
  html_document:
    fig_width: 1
---

These are my notes from "Introduction to Data Science" at Middlebury College in Spring 2023.

+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| Topic                                                                                                                    | Blank\            | Complete\        | Homework\        | Other Resources     |
|                                                                                                                          | Notes\            | Notes\           | Template\        |                     |
|                                                                                                                          | (.Rmd)            | (.pdf)           | (.Rmd)           |                     |
+:=========================================================================================================================+:==================+==================+:=================+:====================+
| Introduction to R, RStudio, and RMarkdown                                                                                | [🖥️](notes.Rmd) \ | [🖥️](notes.Rmd)  | [🖥️](notes.Rmd)  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| wrangling                                                                                                                |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| aggregating                                                                                                              |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| pretty tables with [kableExtra](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html) |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| creating plots with [ggplot2](https://ggplot2.tidyverse.org/) (Part 1)                                                   |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| creating plots with [ggplot2](https://ggplot2.tidyverse.org/) (Part 2)                                                   |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| working with categorical data using [forcats](https://forcats.tidyverse.org/)                                            |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| working with numeric data using [scales](https://scales.r-lib.org/)                                                      |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| joining                                                                                                                  |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| reshaping                                                                                                                |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| maps (cloropleth)                                                                                                        |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| maps (points)                                                                                                            |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| Simple Linear Regression                                                                                                 |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| Multiple Regression                                                                                                      |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| Web Scraping with [rvest](https://rvest.tidyverse.org/) (tables)                                                         |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| Webscraping with [rvest](https://rvest.tidyverse.org/) (text)                                                            |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| Working with text using [stringr](https://stringr.tidyverse.org/)                                                        |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+
| Working with dates and times using [lubridate](https://lubridate.tidyverse.org/)                                         |                   |                  |                  |                     |
+--------------------------------------------------------------------------------------------------------------------------+-------------------+------------------+------------------+---------------------+

**Animation**

-   [.html file](notes/Notes_Animation.html)
-   [.Rmd file](notes/Notes_Animation.Rmd)
-   [Animation - Intro (YouTube Video)](https://youtu.be/kL7Ogq5MKh8)
-   [Animation - gganimate "Gapminder" data (YouTube Video)](https://youtu.be/tCGW49nipQY)
-   [Animation - ease_aes() (YouTube Video)](https://youtu.be/m7MsjJZ_QpI)
-   [Animation - gganimate "Air Quality" data (YouTube Video)](https://youtu.be/X6J8jh-Gdbs)
-   [Animation - more examples (YouTube Video)](https://youtu.be/ZQTK3A2xN2o)
-   [Animation - plotly (YouTube Video)](https://youtu.be/gk5VhST4h_Q)
